// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package order

import (
	"course-api/internal/cart/repository"
	cart2 "course-api/internal/cart/usecase"
	"course-api/internal/discount/repository"
	discount2 "course-api/internal/discount/usecase"
	"course-api/internal/order/delivery/http"
	order2 "course-api/internal/order/repository"
	order3 "course-api/internal/order/usecase"
	"course-api/internal/order_detail/repository"
	order_detail2 "course-api/internal/order_detail/usecase"
	"course-api/internal/payment/usecase"
	"course-api/internal/product/repository"
	product2 "course-api/internal/product/usecase"
	"course-api/pkg/media/cloudinary"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *order.OrderHandler {
	orderRepository := order2.NewOrderRepository(db)
	cartRepository := cart.NewCartRepository(db)
	cartUsecase := cart2.NewCartUsecase(cartRepository)
	discountRepository := discount.NewDiscountRepository(db)
	discountUsecase := discount2.NewDiscountUsecase(discountRepository)
	productRepository := product.NewProductRepository(db)
	mediaMedia := media.NewMediaUsecase()
	productUsecase := product2.NewProductUsecase(productRepository, mediaMedia)
	orderDetailRepository := order_detail.NewOrderDetailRepository(db)
	orderDetailUsecase := order_detail2.NewOrderDetailUsecase(orderDetailRepository)
	paymentUsecase := payment.NewPaymentUsecase()
	orderUsecase := order3.NewOrderUsecase(orderRepository, cartUsecase, discountUsecase, productUsecase, orderDetailUsecase, paymentUsecase)
	orderHandler := order.NewOrderHandler(orderUsecase)
	return orderHandler
}
