// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"course-api/internal/user/delivery/http"
	user2 "course-api/internal/user/repository"
	user3 "course-api/internal/user/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *user.UserHandler {
	userRepository := user2.NewUserRepository(db)
	userUsecase := user3.NewUserUsecase(userRepository)
	userHandler := user.NewUserHandler(userUsecase)
	return userHandler
}
