// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"course-api/internal/product/delivery/http"
	product2 "course-api/internal/product/repository"
	product3 "course-api/internal/product/usecase"
	"course-api/pkg/media/cloudinary"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *product.ProductHandler {
	productRepository := product2.NewProductRepository(db)
	mediaMedia := media.NewMediaUsecase()
	productUsecase := product3.NewProductUsecase(productRepository, mediaMedia)
	productHandler := product.NewProductHandler(productUsecase)
	return productHandler
}
