// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"course-api/internal/admin/delivery/http"
	admin2 "course-api/internal/admin/repository"
	admin3 "course-api/internal/admin/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *admin.AdminHandler {
	adminRepository := admin2.NewAdminRepository(db)
	adminUsecase := admin3.NewAdminUsecase(adminRepository)
	adminHandler := admin.NewAdminHandler(adminUsecase)
	return adminHandler
}
